### ISSUE TITLE
Need to add all pages and images into the same file to link pages together?

### ISSUE THREAD

**Issue by Laurynlau** [Laurynlau/Team28GitHub#2]
I can't figure out how to link pages in different folders from each other. I think they may need to all be in the same folder.

**Comment by ev1sl** [comment]
Use Relative Paths: For a file in a subfolder, link like this: `<a href="subfolder/file.html">Link Text</a>`. If you need to go up a folder, use `..`, like so: `<a href="../file.html">Link Text</a>`.

Organize Your Files Logically: It's not necessary to have all files in one folder, but ensure they're logically organized (e.g., separate folders for images, CSS, JavaScript).

Test Your Links: Check your links in different browsers and environments to make sure they work as expected.

**UPDATE 10/12/23** Mangesh has fixed this issue.
